services:
  - type: web
    name: hostel-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///hostel.db"